# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160304_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dummy_image',
            field=models.CharField(default='http://pixel.nymag.com/imgs/daily/intelligencer/2015/08/10/10-donald-trump-debate.w750.h560.2x.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1),
        ),
    ]
