# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160306_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='next_appointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
