# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_patient_next_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
