# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20160306_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Actise', max_length=9),
        ),
    ]
