# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Recovered', 'Recovered')], default='Active', max_length=9),
        ),
    ]
