# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20160306_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='status',
            new_name='state',
        ),
    ]
