# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20160306_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(choices=[('Good', 'Good'), ('Needs Attention', 'Needs Attention'), ('Check-in', 'Check-in')], default='Good', max_length=50),
        ),
    ]
