# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20160306_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Good', 'Good'), ('Needs Attention', 'Needs Attention'), ('Check-in', 'Check-in')], default='Good', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Recovered', 'Recovered')], default='Active', max_length=50),
        ),
    ]
