# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20160306_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Arm', 'Arm'), ('Shoulder', 'Shoulder'), ('Back', 'Back'), ('Leg', 'Leg'), ('Knee', 'Knee')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=3)),
                ('sets_completed', models.IntegerField(blank=True, null=True)),
                ('reps_total', models.IntegerField(default=15)),
                ('reps_completed', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('range_of_motion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rehab_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Doctor')),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='app_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 14, 51, 40, 236821)),
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_length',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='satus',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Missed', 'Missed'), ('Completed', 'Completed')], default='Upcoming', max_length=50),
        ),
        migrations.AddField(
            model_name='rehab_session',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Patient'),
        ),
        migrations.AddField(
            model_name='exercise_set',
            name='rehab_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Rehab_Session'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Exercise_Set'),
        ),
    ]
