# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20160307_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='satus',
            new_name='status',
        ),
        migrations.AddField(
            model_name='exercise_set',
            name='excercises',
            field=models.CharField(choices=[('Arm', (('Forward Bicep Curl', 'Forward Bicep Curl'), ('Side Bicep Cur', 'Side Bicep Cur'))), ('Shoulder', (('Front Arm Raise', 'Front Arm Raise'), ('Lateral Arm Raise', 'Lateral Arm Raise'))), ('Back', (('Scapular Squeeze', 'Scapular Squeeze'), ('Thoracic Extension', 'Thoracic Extension'))), ('Leg', (('Standing Hamstring Curl', 'Standing Hamstring Curl'), ('Sit to Stand', 'Sit to Stand'))), ('Knee', (('Assisted Knee Flexion', 'Assisted Knee Flexion'), ('Prolonged Knee Extension', 'Prolonged Knee Extension')))], default='Arm', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 15, 31, 51, 195635)),
        ),
    ]
