# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20160307_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehab_session',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Doctor'),
        ),
        migrations.AlterField(
            model_name='rehab_session',
            name='app_date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 15, 53, 59, 728032)),
        ),
    ]
